config/routes.rb
Rails.application.routes.draw do

  resources :accounts do
    get :update_billing, on: :member
  end

  resources :instances do
    get :load_from_aws, on: :collection
    get :start, on: :member
    get :stop, on: :member
  end

  resources :reports

  devise_for :users
  resources :users

  root :to => "visitors#index"

end

app/models/instance.rb
class Instance < ActiveRecord::Base
  belongs_to :account

  def start
    self.account.set_aws_credentials
    ec2 = Aws::EC2::Client.new
    ec2.start_instances( {instance_ids:[self.instance_id]})
    begin
      ec2.wait_until(:instance_running, instance_ids:[self.instance_id])
      return 'instance running'
    rescue Aws::Waiters::Errors::WaiterFailed => error
      return "failed waiting for instance to start: #{error.message}"
    end
  end


  def stop
    self.account.set_aws_credentials
    ec2 = Aws::EC2::Client.new
    ec2.stop_instances( {instance_ids:[self.instance_id]})
    begin
      ec2.wait_until(:instance_stopped, instance_ids:[self.instance_id])
      return 'instance stopped'
    rescue Aws::Waiters::Errors::WaiterFailed => error
      return "failed waiting for instance to stop: #{error.message}"
    end
  end

end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  before_action :set_instance, only: [:show, :edit, :update, :destroy, :start, :stop]

  # GET /instances
  # GET /instances.json
  def index
    @instances = current_account.instances.order(:name).all
  end

  # GET /instances/1
  # GET /instances/1.json
  def show
  end

  def load_from_aws
    current_account.load_from_aws
    redirect_to action: :index
  end

  def start
    flash[:notice] = @instance.start
    redirect_to @instance
  end

  def stop
    flash[:notice] = @instance.stop
    redirect_to @instance
  end

  # GET /instances/new
  def new
    @instance = Instance.new
  end

  # GET /instances/1/edit
  def edit
  end

  # POST /instances
  # POST /instances.json
  def create
    @instance = Instance.new(instance_params)

    respond_to do |format|
      if @instance.save
        format.html { redirect_to @instance, notice: 'Instance was successfully created.' }
        format.json { render :show, status: :created, location: @instance }
      else
        format.html { render :new }
        format.json { render json: @instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instances/1
  # PATCH/PUT /instances/1.json
  def update
    respond_to do |format|
      if @instance.update(instance_params)
        format.html { redirect_to @instance, notice: 'Instance was successfully updated.' }
        format.json { render :show, status: :ok, location: @instance }
      else
        format.html { render :edit }
        format.json { render json: @instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instances/1
  # DELETE /instances/1.json
  def destroy
    @instance.destroy
    respond_to do |format|
      format.html { redirect_to instances_url, notice: 'Instance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instance
      @instance = Instance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instance_params
      params.require(:instance).permit(:account_id, :name, :description, :instance_id, :instance_type, :availability_zone, :dns_address, :current_address)
    end
end

app/helpers/instances_helper.rb
module InstancesHelper
end

app/views/instances/_form.html.haml
= simple_form_for(@instance) do |f|
  = f.error_notification

  .form-inputs
    = f.input :description
    = f.input :dns_address

  .form-actions
    = f.button :submit, class: 'btn btn-primary'
%br

app/views/instances/edit.html.haml
%h2
  Editing instance:
  = @instance.name

= render 'form'

= link_to 'Show', @instance
\|
= link_to 'Back', instances_path

app/views/instances/index.html.haml
%h2 Listing instances

%p= link_to 'Update Instance List', load_from_aws_instances_path, class: 'btn btn-primary'

%table.table
  %tr
    %th Name
    %th Description
    %th Address
    %th Instance
    %th Instance type
    %th Availability zone

  - @instances.each do |instance|
    %tr
      %td
        = link_to instance.name, instance
        %br
        = instance.state
      %td
        = link_to 'Start', start_instance_path(instance), class: 'btn btn-sm btn-success' if instance.state == 'stopped'
        = link_to 'Stop', stop_instance_path(instance), class: 'btn btn-sm btn-danger' if instance.state == 'running'
      %td
        = link_to instance.public_ip_address, "http://#{instance.public_ip_address}", target: '_blank' if instance.public_ip_address.present?
        %br
        = link_to instance.dns_address, "http://#{instance.dns_address}", target: '_blank' if instance.dns_address.present?
      %td= instance.instance_id
      %td= instance.instance_type
      %td= instance.availability_zone

app/views/instances/new.html.haml
%h1 New instance

= render 'form'

= link_to 'Back', instances_path

app/views/instances/show.html.haml
%h2
  Instance:
  = @instance.name

%p#notice= notice

%p
  %b Account:
  = @instance.account
%p
  %b Description:
  = @instance.description
%p
  %b Instance:
  = @instance.instance_id
%p
  %b Instance type:
  = @instance.instance_type
%p
  %b Availability zone:
  = @instance.availability_zone
%p
  %b Dns address:
  = @instance.dns_address
%p
  %b Public IP Address:
  = @instance.public_ip_address
%p
  %b Public DNS Name:
  = @instance.public_dns_name

= link_to 'Edit', edit_instance_path(@instance)
\|
= link_to 'Destroy', @instance, :method => :delete, :data => { :confirm => 'Are you sure?' }
\|
= link_to 'Back', instances_path