config/routes.rb
Rails.application.routes.draw do

  resources :accounts do
    get :update_billing, on: :member
  end

  resources :instances do
    get :load_from_aws, on: :collection
    get :start, on: :member
    get :stop, on: :member
  end

  resources :reports

  devise_for :users
  resources :users

  root :to => "visitors#index"

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :account
  has_many :report_lines
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:account_id, :period, :value)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.haml
= simple_form_for(@report) do |f|
  = f.error_notification

  .form-inputs
    = f.input :account_id
    = f.input :period
    = f.input :value

  .form-actions
    = f.button :submit

app/views/reports/edit.html.haml
%h1 Editing report

= render 'form'

= link_to 'Show', @report
\|
= link_to 'Back', reports_path

app/views/reports/index.html.haml
%h1 Listing reports

%table
  %tr
    %th Account
    %th Period
    %th Value
    %th
    %th
    %th

  - @reports.each do |report|
    %tr
      %td= report.account_id
      %td= report.period
      %td= report.value
      %td= link_to 'Show', report
      %td= link_to 'Edit', edit_report_path(report)
      %td= link_to 'Destroy', report, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Report', new_report_path

app/views/reports/new.html.haml
%h1 New report

= render 'form'

= link_to 'Back', reports_path

app/views/reports/show.html.haml
%p#notice= notice

%p
  %b Account:
  = @report.account_id
%p
  %b Period:
  = @report.period
%p
  %b Value:
  = @report.value

= link_to 'Edit', edit_report_path(@report)
\|
= link_to 'Back', reports_path