config/routes.rb
Rails.application.routes.draw do

  resources :accounts do
    get :update_billing, on: :member
  end

  resources :instances do
    get :load_from_aws, on: :collection
    get :start, on: :member
    get :stop, on: :member
  end

  resources :reports

  devise_for :users
  resources :users

  root :to => "visitors#index"

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  has_many :reports
  has_many :instances

  include Ec2Usage

  attr_accessor :reference_date

  def to_s
    self.name
  end

  def s3_region
    'sa-east-1'
  end

  require 'zip/zip'

  def update_billing_data(reference_date)

    @reference_date = reference_date

    Aws.config.update({
                          region: self.s3_region,
                          credentials: Aws::Credentials.new(self.access_key, self.secret),
                      })

    year = @reference_date.year
    month = @reference_date.month.to_s.rjust(2,'0')
    # curr_month = "#{self.aws_account_id}-aws-billing-csv-#{year}-#{month}.csv"
    # curr_month = "#{self.aws_account_id}-aws-billing-detailed-line-items-#{year}-#{month}.csv.zip"
    curr_month = "#{self.aws_account_id}-aws-billing-detailed-line-items-with-resources-and-tags-#{year}-#{month}.csv.zip"

    s3 = Aws::S3::Client.new
    resp = s3.get_object(bucket:self.bucket_name, key:curr_month)

    Zip::InputStream.open(resp.body) do |unzipped|
      zip_entry = unzipped.get_next_entry
      csv_data = zip_entry.get_input_stream.read
      update_report(csv_data)
    end
  end

  def month_report(date = Date.today)
    period = date.beginning_of_month
    self.reports.where(period: period).first
  end

  def month_to_date_spend
    rep = month_report(@reference_date)
    if rep.present?
      daily_spends = rep.report_lines.where("date <= ?", @reference_date).group('date').sum('unblended_cost')
    end
    month_spend = hash_values_sum(daily_spends)
    month_spend
  end

  def last_month_to_date_spend
    rep = month_report(@reference_date.prev_month)
    if rep.present?
      daily_spends = rep.report_lines.where("date <= ?", @reference_date.prev_month).group('date').group('date').sum('unblended_cost')
    end
    last_month_spend = hash_values_sum(daily_spends)
    last_month_spend
  end

  def month_estimate_spend
    daily_average = day_average_spend
    daily_average * @reference_date.end_of_month.day
  end

  def last_month_spend
    rep = month_report(@reference_date.prev_month)
    if rep.present?
      daily_spends = rep.report_lines.group('date').group('date').sum('unblended_cost')
    end
    last_month_spend = hash_values_sum(daily_spends)
    last_month_spend
  end

  def month_change
    calc_change( month_estimate_spend, last_month_spend )
  end

  def month_to_date_change
    calc_change( month_to_date_spend, last_month_to_date_spend )
  end

  def day_average_spend
    rep = month_report(@reference_date)
    if rep.present?
      daily_spends = rep.report_lines.group('date').sum('unblended_cost')
    end
    daily_average = hash_values_average(daily_spends)
    daily_average
  end

  def previous_average_spend
    rep = month_report(@reference_date.prev_month)
    if rep.present?
      daily_spends = rep.report_lines.group('date').sum('unblended_cost')
    end
    daily_average = hash_values_average(daily_spends)
    daily_average
  end

  def day_average_change
    calc_change(day_average_spend,previous_average_spend)
  end

  def day_spend
    rep = month_report(@reference_date)
    if rep.present?
      daily_spends = rep.report_lines.group('date').sum('unblended_cost')
    end
    if (daily_spends.present?)
      daily_spends[@reference_date]
    else
      0
    end
  end

  def previous_day_spend
    rep = month_report(@reference_date)
    if rep.present?
      daily_spends = rep.report_lines.group('date').sum('unblended_cost')
    end
    if (daily_spends.present?)
      daily_spends[@reference_date.prev_day]
    else
      nil
    end
  end

  def month_to_date_group_by_service
    month_to_date_group_by('service')
  end

  def month_to_date_group_by_custo
    month_to_date_group_by('custo')
  end

  def day_spend_change
    calc_change(day_spend,previous_day_spend)
  end

  def last_update
    rep = month_report
    month_report.updated_at if rep
  end

  def day_spend_moving_averages
    ret = []
    ret << {:name => 'Média móvel de 5 dias', :data => day_spend_moving_average(5)}
    ret << {:name => 'Média móvel de 15 dias', :data => day_spend_moving_average(15)}
    ret << {:name => 'Média móvel de 45 dias', :data => day_spend_moving_average(45)}
    ret
  end

  def spend_by_service_over_time
    ret = []
    rep = month_report(@reference_date)
    if rep.present?
      series = {}
      daily_spends = rep.report_lines.where("date <= ?", @reference_date).group('service').group('date').sum('unblended_cost')
      if (daily_spends.present?)
        daily_spends.each do |k, v|
          spend = {} if series[k[0]].blank?
          spend = series[k[0]] if series[k[0]].present?
          if (v > 0)
            spend[k[1]] = v
            series[k[0]] = spend
          end
        end
      end

      series.each do |k, v|
        ret << {:name => k, :data => v}
      end
    end
    ret
  end


  # Deliver daily reports for all accounts
  def self.deliver_daily_reports
    Account.all.each do |account|
      UserMailer.daily_report(account).deliver
    end
  end



  # ****************
  # private section
  # ****************

  private
    def update_report(csv_data)
      period = @reference_date.beginning_of_month
      if period == Date.today.beginning_of_month
        day = @reference_date.day
      else
        # se não é o mes corrente, days e o numero de dias no mês
        day = @reference_date.end_of_month.day
      end
      rep = self.reports.where(period:period).first
      rep = self.reports.create(period:period) unless rep

      parse_billing_data(csv_data, rep)

      rep.reference_day = day

      rep.save!
    end

    require 'csv'

    def parse_billing_data(csv_data, report)
      csv = CSV.new(csv_data, :headers => true)
      #  hash usado para armazenar a AZ por resource-id pois, dependendo da operacao, um mesmo recurso pode ou nao ter a informacao de AZ na planilha da AWS
      az_by_resource_id = {}
      dates = {}
      csv.each do |row|
        r = row.to_hash
        # nao quero contabilizar os descontos da Dedalus
        if r['RecordType'] == 'LineItem' && !r['ItemDescription'].downcase.include?('reseller program discount')
          # dates
          record_date = r['UsageStartDate'].slice(0,10)
          if (dates[record_date].present?)
            report_lines_for_this_date = dates[record_date]
          else
            report_lines_for_this_date = {}
          end
          # report_lines
          # agregando por 'servico-resourceId'. Ex: 'Ec2 EBS-i-87a347'
          service_name = define_service_name(r)
          resource_id = r['ResourceId']
          report_line_key = "#{service_name}-#{resource_id}"
          if (report_lines_for_this_date[report_line_key].present?)
            report_line = report_lines_for_this_date[report_line_key]
          else
            parsed_date = Date.parse(record_date, '%Y-%m-%d')
            ReportLine.where(:service => service_name).where(:resource_id => resource_id).where(:date => parsed_date).destroy_all
            report_line = ReportLine.new
            report_line.product_name = r['ProductName']
            report_line.resource_id = resource_id
            report_line.resource_name = r['user:Name'] || r['user:name']
            if (r['AvailabilityZone'].present?)
              az_by_resource_id[resource_id] = r['AvailabilityZone']
            end
            report_line.az = az_by_resource_id[resource_id]
            report_line.custo = r['user:custo']
            report_line.service = service_name
            report_line.blended_cost = 0
            report_line.unblended_cost = 0
            report_line.date = parsed_date
          end

          report_line.blended_cost += r['BlendedCost'].to_f if r['BlendedCost'].present?
          report_line.unblended_cost += r['UnBlendedCost'].to_f if r['UnBlendedCost'].present?

          report_lines_for_this_date[report_line_key] = report_line
          dates[record_date] = report_lines_for_this_date
        end
      end

      report_lines = []
      dates.each do |date, report_lines_for_this_date|
        report_lines << report_lines_for_this_date.values
      end

      report.report_lines = report_lines.flatten
    end

    def define_service_name(row)
      if (row['ProductName'] == 'Amazon Elastic Compute Cloud')
        usage_type = row['UsageType']
        if row['UsageType'].downcase.include?('boxusage') || row['UsageType'].downcase.include?('heavyusage') || row['UsageType'].downcase.include?('spotusage')
          return 'EC2 Instance Usage'
        elsif row['UsageType'].downcase.include?('cw')
          return 'EC2 Cloud Watch'
        elsif row['UsageType'].downcase.include?('ebs')
          return 'EC2 EBS'
        elsif row['UsageType'].downcase.include?('datatransfer')
          return 'EC2 Data Transfer'
        elsif row['UsageType'].downcase.include?('cloudfront')
          return 'EC2 CloudFront'
        elsif row['UsageType'].downcase.include?('dataprocessing') || row['UsageType'].downcase.include?('loadbalancer')
          return 'EC2 Load Balancer'
        else
          return 'EC2 Others'
        end
      else
        return row['ProductName']
      end
    end

    def day_spend_moving_average(window_size)
      begin_date = @reference_date - (30+window_size).days
      daily_spends = ReportLine.where('date >= ?', begin_date).where('date <= ?', @reference_date).group('date').sum('unblended_cost')
      hash_moving_average(daily_spends, window_size)
    end

    def hash_moving_average(hash, window_size)
      if (hash.present?)
        hash_moving_average = {}
        hash = hash.sort.to_h
        hash.each_with_index do |kv, pos|
          next if (pos < (window_size-1))
          moving_average = 0
          for i in (pos - (window_size-1))..pos
            moving_average += hash[hash.keys[i]]
          end
          moving_average = moving_average / window_size
          hash_moving_average[kv[0]] = moving_average
        end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_billing
    account = current_user.account
    reference_date = Date.parse(params[:ref_date], '%Y-%m-%d') if params[:ref_date].present?
    reference_date = Date.today if reference_date.blank?
    account.update_billing_data(reference_date)

    redirect_to root_url(:ref_date => params[:ref_date])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name, :aws_account_id, :bucket_name, :access_key, :secret, :user_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.haml
= simple_form_for(@account) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :aws_account_id
    = f.input :bucket_name
    = f.input :access_key
    = f.input :secret
    = f.association :user

  .form-actions
    = f.button :submit, class: 'btn btn-primary'
%br

app/views/accounts/_indicator_panel.haml
.panel.panel-default
  .panel-heading
    = title
  .panel-body
    %span.current-value
      = "US$ #{format_number value}"
    %span.difference
      = format_variation difference
    %p.previous-title
      = previous_title
      %span.previous-value
        = format_number previous_value

app/views/accounts/_status.haml
%h2
  = @account.name
  \:
  = @account.reference_date.strftime("%B")
%h6
  = @account.reference_date
%br
= render  'accounts/indicator_panel', title: 'Custo Até o momento', value: @account.month_to_date_spend, difference:  @account.month_to_date_change, previous_title: 'No mês anterior foi', previous_value: @account.last_month_to_date_spend
= render  'accounts/indicator_panel', title: 'Valor Estimado para o mês', value:  @account.month_estimate_spend, difference: @account.month_change, previous_title: 'Valor do mês anterior foi', previous_value: @account.last_month_spend
= render  'accounts/indicator_panel', title: 'Média diária', value:  @account.day_average_spend, difference: @account.day_average_change, previous_title: 'A média diária do mês anterior foi', previous_value: @account.previous_average_spend
= render  'accounts/indicator_panel', title: 'Custo do dia', value:  @account.day_spend, difference: @account.day_spend_change, previous_title: 'O custo do dia anterior foi', previous_value: @account.previous_day_spend

%h3
  Custo por serviço
= pie_chart @account.month_to_date_group_by_service

%h3
  Custo por centro de custo
= pie_chart @account.month_to_date_group_by_custo

%h3
  Tendência do custo
= line_chart @account.day_spend_moving_averages

%h3
  Evolução do custo por serviço
= line_chart @account.spend_by_service_over_time

app/views/accounts/edit.html.haml
%h1 Editing account

= render 'form'

= link_to 'Show', @account
\|
= link_to 'Back', accounts_path

app/views/accounts/index.html.haml
%h1 Accounts

%table.table
  %tr
    %th Name
    %th Aws account
    %th

  - @accounts.each do |account|
    %tr
      %td= account.name
      %td= account.aws_account_id
      %td
        = link_to 'Show', account
        |
        = link_to 'Edit', edit_account_path(account)
        |
        = link_to 'Destroy', account, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Account', new_account_path, class: 'btn btn-primary'

app/views/accounts/new.html.haml
%h1 New account

= render 'form'

= link_to 'Back', accounts_path

app/views/accounts/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @account.name
%p
  %b Aws account:
  = @account.aws_account_id
%p
  %b Bucket name:
  = @account.bucket_name
%p
  %b Access key:
  = @account.access_key
%p
  %b Secret:
  = @account.secret
%p
  %b Responsible User:
  = @account.user.email


= link_to 'Edit', edit_account_path(@account)
\|
= link_to 'Back', accounts_path